#!/usr/bin/bash
CURRENT_WALLPAPER=$(cat ~/.cache/wal/wal)
while true
do
    WALLPAPER=$(find ~/.local/wallpapers/ -type f | shuf -n 1)
    if [ $CURRENT_WALLPAPER != $WALLPAPER ]
    then
        wal -i $WALLPAPER
        feh --bg-scale $WALLPAPER
        killall nm-applet; nm-applet &
        killall pasystray; pasystray &
        xdotool key alt+F5
        exit
    fi
done
